name: Auto Bestil Tømning

on:
  schedule:
    - cron: "0 9 * * 5" # fredag kl 09
  workflow_dispatch:

jobs:
  order:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node order.js

      - name: Upload screenshot on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: error.png
